import fs from 'fs/promises'
import path from 'path'
import { fileURLToPath } from 'url'
import { models } from '@/models/registry/models'
import {
  buildCapabilities,
  buildModelConstants,
  collectApiOperationsFromSources,
  collectDependencies,
  mergeRegistryOperations,
  toGradleVersionCatalog,
  toKotlinApi
} from './generate-utils'
import {
  androidManifestSourceSchema,
  generatedAndroidManifestSchema,
  type AndroidManifestSource,
  type GeneratedAddonCapability,
  type GeneratedApiOperation,
  type GeneratedAndroidManifest,
  type GeneratedDependency
} from './types'

type PackageJson = {
  name: string
  version: string
  dependencies?: Record<string, string>
  peerDependencies?: Record<string, string>
}

const scriptDir = fileURLToPath(new URL('.', import.meta.url))
const sdkDir = path.resolve(scriptDir, '../..')
const sourceManifestPath = path.join(sdkDir, 'android', 'manifest.source.json')
const packageJsonPath = path.join(sdkDir, 'package.json')
const generatedDir = path.join(sdkDir, 'android', 'generated')
const schemasDir = path.join(sdkDir, 'schemas')
const handlerRegistryPath = path.join(sdkDir, 'server', 'rpc', 'handler-registry.ts')

const outputFiles = {
  manifest: path.join(generatedDir, 'qvac-sdk-manifest.json'),
  capabilities: path.join(generatedDir, 'capabilities.json'),
  modelConstants: path.join(generatedDir, 'models-catalog.json'),
  apiContract: path.join(generatedDir, 'api-contract.json'),
  gradleVersionCatalog: path.join(generatedDir, 'libs.versions.toml'),
  kotlinInfo: path.join(generatedDir, 'GeneratedQvacSdkInfo.kt'),
  kotlinApi: path.join(generatedDir, 'GeneratedQvacApi.kt'),
  addonManifest: path.join(generatedDir, 'addon-manifest.json')
} as const

async function readJsonFile<T>(filePath: string): Promise<T> {
  const content = await fs.readFile(filePath, 'utf8')
  return JSON.parse(content) as T
}

function createGeneratedManifest(
  packageJson: PackageJson,
  source: AndroidManifestSource,
  dependencies: GeneratedDependency[],
  capabilities: GeneratedAddonCapability[]
): GeneratedAndroidManifest {
  return {
    schemaVersion: 1,
    sourceSchemaVersion: source.schemaVersion,
    generatedAt: `sdk-version-${packageJson.version}`,
    sdk: {
      packageName: '@qvac/sdk',
      version: packageJson.version
    },
    android: source.android,
    runtime: source.runtime,
    dependencies,
    capabilities
  }
}

async function collectApiOperations(): Promise<GeneratedApiOperation[]> {
  const fileNames = (await fs.readdir(schemasDir)).filter((name) => name.endsWith('.ts')).sort()
  const sourceFiles: Array<{ fileName: string; content: string }> = []
  for (const fileName of fileNames) {
    const sourceFile = path.join(schemasDir, fileName)
    const content = await fs.readFile(sourceFile, 'utf8')
    sourceFiles.push({
      fileName,
      content
    })
  }

  const fromSchemas = collectApiOperationsFromSources(sourceFiles)
  const registrySource = await fs.readFile(handlerRegistryPath, 'utf8')
  return mergeRegistryOperations(fromSchemas, registrySource)
}

function toKotlinInfo(manifest: GeneratedAndroidManifest): string {
  const abiList = manifest.android.abis.join(', ')
  return `// AUTO-GENERATED BY scripts/android/generate.ts
// DO NOT MODIFY MANUALLY

package ${manifest.android.kotlinPackage}

object GeneratedQvacSdkInfo {
  const val VERSION = "${manifest.sdk.version}"
  const val GROUP_ID = "${manifest.android.groupId}"
  const val ARTIFACT_ID = "${manifest.android.artifactId}"
  const val NAMESPACE = "${manifest.android.namespace}"
  const val MIN_SDK = ${manifest.android.minSdk}
  const val TARGET_SDK = ${manifest.android.targetSdk}
  const val COMPILE_SDK = ${manifest.android.compileSdk}
  const val ABIS = "${abiList}"
}
`
}

function toAddonManifest(capabilities: GeneratedAddonCapability[]): string {
  const addonManifest = {
    schemaVersion: 1,
    addons: capabilities.map((capability) => ({
      addon: capability.addon,
      androidSupported: capability.androidSupported,
      fallbackBehavior: capability.fallbackBehavior
    }))
  }
  return `${JSON.stringify(addonManifest, null, 2)}\n`
}

async function readIfExists(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, 'utf8')
  } catch {
    return null
  }
}

async function ensureDirectory(directoryPath: string): Promise<void> {
  await fs.mkdir(directoryPath, { recursive: true })
}

async function writeFileIfChanged(filePath: string, content: string): Promise<boolean> {
  const previous = await readIfExists(filePath)
  if (previous === content) return false
  await fs.writeFile(filePath, content)
  return true
}

async function checkFileMatches(filePath: string, expected: string): Promise<boolean> {
  const current = await readIfExists(filePath)
  return current === expected
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes('--check')
  const sourceRaw = await readJsonFile<unknown>(sourceManifestPath)
  const source = androidManifestSourceSchema.parse(sourceRaw)
  const packageJson = await readJsonFile<PackageJson>(packageJsonPath)

  if (packageJson.name !== '@qvac/sdk') {
    throw new Error(`Expected package name @qvac/sdk, got ${packageJson.name}`)
  }

  const dependencies = collectDependencies(packageJson, source)
  const capabilities = buildCapabilities(source, models)
  const generatedManifest = generatedAndroidManifestSchema.parse(
    createGeneratedManifest(packageJson, source, dependencies, capabilities)
  )
  const modelConstants = buildModelConstants(models)
  const apiOperations = await collectApiOperations()

  const manifestJson = `${JSON.stringify(generatedManifest, null, 2)}\n`
  const capabilitiesJson = `${JSON.stringify(generatedManifest.capabilities, null, 2)}\n`
  const modelConstantsJson = `${JSON.stringify(modelConstants, null, 2)}\n`
  const apiContractJson = `${JSON.stringify(apiOperations, null, 2)}\n`
  const gradleToml = toGradleVersionCatalog(generatedManifest.dependencies, generatedManifest)
  const kotlinInfo = toKotlinInfo(generatedManifest)
  const kotlinApi = toKotlinApi(apiOperations)
  const addonManifest = toAddonManifest(generatedManifest.capabilities)

  const outputs: Record<string, string> = {
    [outputFiles.manifest]: manifestJson,
    [outputFiles.capabilities]: capabilitiesJson,
    [outputFiles.modelConstants]: modelConstantsJson,
    [outputFiles.apiContract]: apiContractJson,
    [outputFiles.gradleVersionCatalog]: gradleToml,
    [outputFiles.kotlinInfo]: kotlinInfo,
    [outputFiles.kotlinApi]: kotlinApi,
    [outputFiles.addonManifest]: addonManifest
  }

  if (checkMode) {
    let hasDrift = false
    const outputPaths = Object.keys(outputs).sort((a, b) => a.localeCompare(b))
    for (const outputPath of outputPaths) {
      const matches = await checkFileMatches(outputPath, outputs[outputPath]!)
      if (!matches) {
        hasDrift = true
        console.log(`OUTDATED ${path.relative(sdkDir, outputPath)}`)
      }
    }
    if (hasDrift) {
      process.exitCode = 1
      return
    }
    console.log('Android generated files are up to date')
    return
  }

  await ensureDirectory(generatedDir)
  const outputPaths = Object.keys(outputs).sort((a, b) => a.localeCompare(b))
  let changed = 0
  for (const outputPath of outputPaths) {
    const didWrite = await writeFileIfChanged(outputPath, outputs[outputPath]!)
    if (didWrite) {
      changed += 1
      console.log(`UPDATED ${path.relative(sdkDir, outputPath)}`)
    } else {
      console.log(`UNCHANGED ${path.relative(sdkDir, outputPath)}`)
    }
  }
  console.log(`android:sync complete (${changed} file${changed === 1 ? '' : 's'} changed)`)
}

main().catch((error) => {
  console.error(error)
  process.exitCode = 1
})
